### ISSUE TITLE
Suggestions for the repo

### ISSUE THREAD

**Issue by 4rnaudB** [shimming-toolbox/susceptibility-to-fieldmap-fft#12]
### Installation
- Add a create and activate environment before the pip install (see https://github.com/shimming-toolbox/Teensy-communication for example)

### Usage
- Either add a change directory step or call the full path to the script (./fft_simulation/analytical_cases.py instead of analytical_cases.py)

### Figures
- Add titles when missing
- Remove axes for Figure 1 of analytical_cases.py

### FFT simulations
- Change the example path directory to using forward slashes ( / ) instead of back slashes ( \ ) and change the path to something like outpath/susceptibilities.nii.gz 

### analytical_cases.py
- Add function descriptions
- Mask using the [] operator
- Create a plot() function in your class and just call object.plot() to avoid duplicating code. You can create a global dictionary with these parameters: {'sphere: Sphere, 'cylinder': Cylinder} and create the object with the input to the function by doing dict{geometry_type}(parameters)

### fft_simulations.py
- using split('.') function to look at file type would be cleaner than [:-4]

**Comment by CharlesPageot** [comment]
Thanks for the suggestions, I'll look into it!

**Comment by 4rnaudB** [comment]
Don't hesitate to ask if one of the suggestions is unclear :)

**Comment by CharlesPageot** [comment]
About the use of the [] operator for masks, I'm not really sure what you meant. I used the np.where() function when I apply the masks because I want to specify a value for True and for False.

**Comment by 4rnaudB** [comment]
You can do something like data[mask] = value
