### ISSUE TITLE
Compare fieldmap with matlab code

### ISSUE THREAD

**Issue by CharlesPageot** [shimming-toolbox/susceptibility-to-fieldmap-fft#3]
Compare the Python implementation with Eva's matlab code (see [Fourier-based-field-estimation](https://github.com/evaalonsoortiz/Fourier-based-field-estimation)).

**Comment by CharlesPageot** [comment]
After running the two codes on a whole body susceptibility distribution provided by Sebastian, I noticed a small offset between the fieldmap produced. Turns out, my implementation missed the background field offset (which correspond to the center point of the k-space). After this small change, I obtain the same results from the Matlab and the Python code.

![fieldmap_comparison](https://github.com/shimming-toolbox/susceptibility-to-fieldmap-fft/assets/167803616/4c0875f5-072d-41ec-882a-cd69888fc0c9)
*Figure 1: Absolute difference between the fieldmaps produced by the Matlab and the Python code*

### Some results:

**Maximum difference:** 4.8e-07 ppm
**Minimum difference:** 8.3e-17 ppm
**Mean difference:** 2.1e-08 ppm

**Comment by CharlesPageot** [comment]
@evaalonsoortiz Do you think the error is small enough ?

**Comment by evaalonsoortiz** [comment]
Definitely!  This difference is in ppm, so e^-6, therefore the mean difference is of the order of e^-14? That's definitely "small enough".
