### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by evaalonsoortiz** [shimming-toolbox/susceptibility-to-fieldmap-fft#5]
The README for the matlab-based version of this code is very extensive and educational (https://github.com/evaalonsoortiz/Fourier-based-field-estimation). I propose we copy it to this repo.

**Comment by CharlesPageot** [comment]
Indeed. The theory section of the [Fourier-based-field-estimation](https://github.com/evaalonsoortiz/Fourier-based-field-estimation) code could be copy here. How should I proceed to reference the Matlab code in the README? Is it enough to directly cite it at the begining ?

**Comment by evaalonsoortiz** [comment]
You could copy it to the README of this repo and update whatever needs to be updated so that it references code in this repo.
